#!/bin/bash
#
#   This file echoes a bunch of color codes to the 
#   terminal to demonstrate what's available.  Each 
#   line is the color code of one forground color,
#   out of 17 (default + 16 escapes), followed by a 
#   test use of that color on all 17 background 
#   colors (default + 16 escapes).
#

T='TiP'   # The test text

bg_colors=(
    "40m"
    "100m"
    "41m"
    "101m"
    "42m"
    "102m"
    "43m"
    "103m"
    "44m"
    "104m"
    "45m"
    "105m"
    "46m"
    "106m"
    "47m"
    "107m"
)

fg_colors=(
    "m"
    "1m"
    "30m"
    "90m"
    "31m"
    "91m"
    "32m"
    "92m"
    "33m"
    "93m"
    "34m"
    "94m"
    "35m"
    "95m"
    "36m"
    "96m"
    "37m"
    "97m"
)

# print column headers
echo -en "\n          "
IFS=""
for bg in ${bg_colors[*]}; do printf '% 8s' $bg; done; echo

# print rows
IFS=""
for fg in ${fg_colors[*]}; do
    printf " % 3s \e[$fg  $T  " $fg
    for bg in ${bg_colors[*]}; do
        printf "$EINS \e[$fg\e[$bg  $T  \e[0m";
    done
    echo;
done
echo
