#!/usr/bin/node

import assert from "assert";

async function readStdin() {
  return new Promise((resolve) => {
    let data = "";

    process.stdin.setEncoding("utf8");

    process.stdin.on("data", (chunk) => {
      data += chunk;
    });

    process.stdin.on("end", () => {
      resolve(data);
    });
  });
}

async function main() {
  const arg = process.argv[2];

  const input = arg !== undefined ? arg : await readStdin();

  const cookies = Object.fromEntries(
    input.split("; ").map((row) => {
      const eqIdx = row.indexOf("=");
      assert(eqIdx >= 0);
      return [row.slice(0, eqIdx), decodeURIComponent(row.slice(eqIdx + 1))];
    }),
  );

  console.log(JSON.stringify(cookies, undefined, 2));
}

main();
