#!/usr/bin/python3

import sys
from pathlib import Path

sys.path.append(str(Path(__file__).absolute().parent.parent))

from spt_gfx import Screen, KeyEvent
from spt_gfx import color
import logging
import traceback

if __name__ == "__main__":
    screen: Screen = None

    try:
        screen = Screen()
        screen.open()

        screen.setString(1, 1, "Waiting for key events...")

        def onUpdate(this: Screen):
            this.setString(1, 3, "Press <C-D> to exit.")
        screen.update = onUpdate

        def onKeyPressed(keyEvent: KeyEvent):
            screen.clear()
            screen.setString(1, 1, str(keyEvent))
            screen.refresh()

        screen.addKeyListener(onKeyPressed)

        screen.refresh()
    except:
        if screen is not None:
            screen.close()
        logging.error(traceback.format_exc())
