#!/usr/bin/bash

RESIZE_SIZE=${1:?Missing resize size}

RESIZE_PARAMS_X=0
RESIZE_PARAMS_Y=0

DIRECTION=${2:?Missing move direction}
case $DIRECTION in
l)
	RESIZE_PARAMS_X=-$RESIZE_SIZE
	;;
r)
	RESIZE_PARAMS_X=$RESIZE_SIZE
	;;
u)
	RESIZE_PARAMS_Y=-$RESIZE_SIZE
	;;
d)
	RESIZE_PARAMS_Y=$RESIZE_SIZE
	;;
*)
	echo "kbye"
	return 1
	;;
esac

ACTIVE_WINDOW=$(hyprctl activewindow -j)
IS_FLOATING=$(echo "$ACTIVE_WINDOW" | jq .floating)

if [ "$IS_FLOATING" = "true" ]; then
	hyprctl dispatch "hl.dsp.window.move({
		x = $RESIZE_PARAMS_X,
		y = $RESIZE_PARAMS_Y,
		relative = true
	})"
else
	hyprctl dispatch "hl.dsp.window.move({ direction = '$DIRECTION' })"
fi
