#!/usr/bin/bash

hyprctl dispatch "hl.dsp.window.cycle_next({$(
    if [[ $(hyprctl activewindow -j | jq ."floating") == "true" ]]; then
      echo "tiled = true"; else echo "floating = true";
    fi
  )})"
